services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mosquitto:/etc/mosquitto
      - ./data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  opcua-server:
    build: ./opcua-server
    ports:
      - "4840:4840"
  database-server:
    image: ghcr.io/j-shw/database-server:latest
    build: ./database-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  analysis-system:
    image: ghcr.io/j-shw/analysis-system:latest
    build: ./analysis-system
    ports:
      - "9090:9090"
    depends_on:
      - database-server
    environment:
      DATABASE_URL: "postgres:password@database-server"
  device-management-system:
    image: ghcr.io/j-shw/device-management-system:latest
    build: ./device-management-system
    ports:
      - "9002:9002"
    depends_on:
      - database-server
    environment:
      DATABASE_URL: "postgres:password@database-server"
  front-end:
    image: ghcr.io/j-shw/front-end:latest
    build: ./front-end
    ports:
      - "8080:8080"
  communication-system:
    image: ghcr.io/j-shw/communication-system:latest
    build: ./communication-system
    depends_on:
      - mosquitto
      - front-end
      - analysis-system
    environment:
      MQTT_BROKER_HOST: mosquitto
      DATABASE_URL: "postgres:password@database-server"

  iot-emulator:
    image: ghcr.io/j-shw/iot-emulator:latest
    build: ./iot-emulator
    depends_on:
      - mosquitto
      - opcua-server
      - device-management-system
    environment:
      MQTT_BROKER_HOST: mosquitto
      OPC_UA_SERVER_HOST: opcua-server