services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mosquitto:/etc/mosquitto
      - ./data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  opcua:
    build: ./opcua-server
    ports:
      - "4840:4840"
  db:
    image: ghcr.io/j-shw/database-server:latest
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  analysis:
    image: ghcr.io/j-shw/analysis-system:latest
    build: ./analysis
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres:password@db"
  devices:
    image: ghcr.io/j-shw/device-management-system:latest
    build: ./devices
    ports:
      - "9002:9002"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres:password@db"
  web:
    image: ghcr.io/j-shw/web-ui:latest
    build: ./web
    ports:
      - "8080:8080"
  communication:
    image: ghcr.io/j-shw/communication-system:latest
    build: ./communication
    depends_on:
      - mosquitto
      - web
      - analysis
    environment:
      MQTT_BROKER_HOST: mosquitto
      DATABASE_URL: "postgres:password@db"

  fake-data:
    image: ghcr.io/j-shw/fake-data-system:latest
    build: ./fake-data
    depends_on:
      - mosquitto
      - opcua
      - devices
    environment:
      MQTT_BROKER_HOST: mosquitto
      OPC_UA_SERVER_HOST: opcua