services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mosquitto:/etc/mosquitto
      - ./data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  db:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  analysis:
    build: ./analysis
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres:password@db"
  devices:
    build: ./devices
    ports:
      - "9002:9002"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres:password@db"
  web-socket:
    build: ./web-socket
    ports:
      - "8000:8000"
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - web-socket
  
  communication:
    build: ./communication
    depends_on:
      - mosquitto
      - web-socket
      - analysis
    environment:
      MQTT_BROKER_HOST: mosquitto

  fake-data:
    build: ./fake-data
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER_HOST: mosquitto